"""What a skill is worth, in weapon damage.

Issue #107. The design said every weapon type paired with every damage type
produces a set of skills, and never said what any of them was worth, so every
weapon damage figure in this project was really weapon-and-skill together.
"""

from __future__ import annotations

import csv
import pathlib
import re

import pytest

from cataclysm_sim import affixes as af
from cataclysm_sim import character as ch

WEAPON_SKILLS = (pathlib.Path(__file__).resolve().parents[2]
                 / "game" / "Data" / "WeaponSkills.csv")


# --------------------------------------------------------------------------
# The slots themselves
# --------------------------------------------------------------------------

def test_the_slots_match_the_design_documents_table():
    """`Cataclysm_GDD_v2.md` lists seven rows in its Skill Slots table."""
    assert set(ch.SKILL_SLOTS) == {"Basic", "Heavy", "Special", "Support",
                                   "Aura", "Ultimate", "Movement"}


def test_a_player_chooses_six_of_them():
    """The design says six slots and that the basic attack is automatic, so the
    seventh is not one a player spends."""
    assert len(ch.CHOSEN_SKILL_SLOTS) == 6
    assert ch.BASIC_ATTACK_SLOT not in ch.CHOSEN_SKILL_SLOTS


def test_that_slot_list_check_actually_fires():
    real = dict(ch.SKILL_SLOTS)
    ch.SKILL_SLOTS.pop("Aura")
    try:
        with pytest.raises(ValueError, match="drifted from the design"):
            ch._check_the_slots_match_the_design_document()
    finally:
        ch.SKILL_SLOTS.clear()
        ch.SKILL_SLOTS.update(real)


def test_the_basic_attack_is_exactly_one_hundred_percent():
    """It is the anchor. Every damage figure already fitted -- the tier 8 target,
    the affix values, what a weapon must supply -- was fitted to an ordinary hit,
    and an ordinary hit is the basic attack. If this stopped being 100%, all of
    them would silently mean something else."""
    basic = ch.SKILL_SLOTS[ch.BASIC_ATTACK_SLOT]
    assert basic.typical_damage == basic.lowest == basic.highest == 100.0


def test_that_anchor_check_actually_fires():
    real = ch.SKILL_SLOTS[ch.BASIC_ATTACK_SLOT]
    ch.SKILL_SLOTS[ch.BASIC_ATTACK_SLOT] = ch.SkillSlot(
        "Basic", 120.0, 120.0, 120.0, "moved")
    try:
        with pytest.raises(ValueError, match="must be exactly 100%"):
            ch._check_the_basic_attack_is_the_anchor()
    finally:
        ch.SKILL_SLOTS[ch.BASIC_ATTACK_SLOT] = real


@pytest.mark.parametrize("slot", sorted(ch.SKILL_SLOTS))
def test_every_slots_typical_value_sits_inside_its_own_band(slot):
    s = ch.SKILL_SLOTS[slot]
    assert s.lowest <= s.typical_damage <= s.highest


def test_a_band_that_does_not_contain_its_typical_value_is_rejected():
    with pytest.raises(ValueError, match="outside its"):
        ch.SkillSlot("Bad", 500.0, 100.0, 200.0, "impossible")


def test_the_ultimate_is_the_biggest_hit_and_support_the_smallest():
    """A skill on a long cooldown should be worth more per use than one that is
    off cooldown constantly, and a buff should not be a damage skill."""
    typical = {n: s.typical_damage for n, s in ch.SKILL_SLOTS.items()}
    assert typical["Ultimate"] == max(typical.values())
    assert typical["Support"] == min(typical.values())
    assert typical["Heavy"] > typical["Special"] > typical["Basic"]


# --------------------------------------------------------------------------
# The numbers came out of the designed skills, not out of nowhere
# --------------------------------------------------------------------------

def stated_multipliers(damage_type: str | None = None) -> dict[str, float]:
    """Every skill in the data whose description states a weapon multiplier.

    THIS READS THE GAME DATA, which the simulation package itself never does and
    should not start doing. It is here because these three tests exist to prove
    the slot values were derived from the designed skills rather than invented,
    and that claim cannot be checked against anything else.

    Pass a damage type to restrict the answer to it. The War set is the evidence
    the slot bands were read off, so the test below pins that set exactly; every
    damage type designed afterwards is checked against the bands instead, which
    is the direction the evidence actually runs.
    """
    if not WEAPON_SKILLS.exists():
        raise AssertionError(
            f"{WEAPON_SKILLS} is missing, so the claim that the skill slot "
            "values came from the designed skills cannot be checked. It is "
            "generated by tools/generate_datatables.py.")
    found = {}
    with WEAPON_SKILLS.open(encoding="utf-8-sig") as handle:
        for row in csv.DictReader(handle):
            if damage_type is not None and row["DamageType"] != damage_type:
                continue
            match = re.search(r"(\d+)%\s+weapon damage",
                              row["SkillDescription"] or "", re.I)
            if match:
                found[row["SkillName"]] = float(match.group(1))
    return found


def test_the_designed_skills_already_state_weapon_damage_multipliers():
    """This is why the concept was not invented here. Four of the 61 designed
    War skills in `game/Data/WeaponSkills.csv` say what they are worth in prose.

    Pinned to War on purpose. War was the only complete damage type when the
    slot bands were derived, so it is the evidence for them. A later damage type
    stating its own figure is not evidence and must not silently widen a band;
    it is checked against the bands by the two tests below instead.
    """
    stated = stated_multipliers("War")
    assert stated == {"Haymaker": 100.0, "Bulwark": 200.0,
                      "Annihilator": 300.0, "Skull Splitter": 500.0}


def test_the_ultimate_band_is_the_two_designed_ultimates():
    """Derived rather than picked. Annihilator states 300% and Skull Splitter
    states 500%, so the band is exactly those two."""
    ultimate = ch.SKILL_SLOTS["Ultimate"]
    stated = stated_multipliers()
    assert ultimate.lowest == stated["Annihilator"] == 300.0
    assert ultimate.highest == stated["Skull Splitter"] == 500.0


def test_every_designed_multiplier_fits_inside_some_slots_band():
    """A stated figure outside every band would mean the bands are wrong."""
    bands = [(s.lowest, s.highest) for s in ch.SKILL_SLOTS.values()]
    for name, value in stated_multipliers().items():
        assert any(low <= value <= high for low, high in bands), (
            f"{name} states {value}% and no slot's band contains it")


# --------------------------------------------------------------------------
# A skill knows what it is worth
# --------------------------------------------------------------------------

def test_a_skill_takes_its_slots_value_unless_it_states_its_own():
    assert ch.Skill(name="Swing").weapon_damage_percent() == 100.0
    assert ch.Skill(name="Cleave", slot="Heavy").weapon_damage_percent() == 250.0
    assert ch.Skill(name="Skull Splitter", slot="Ultimate",
                    damage_multiplier=500.0).weapon_damage_percent() == 500.0


def test_a_skill_in_a_slot_that_does_not_exist_is_rejected():
    with pytest.raises(ValueError, match="expected one of"):
        ch.Skill(name="Odd", slot="Passive")


def test_a_skill_dealing_less_than_no_damage_is_rejected():
    with pytest.raises(ValueError, match="less than none"):
        ch.Skill(name="Odd", slot="Heavy", damage_multiplier=-50.0)


def test_a_support_skill_may_still_state_damage_of_its_own():
    """The slot's typical value is zero because most buffs deal none, not
    because a support skill is forbidden from dealing any."""
    assert ch.SKILL_SLOTS["Support"].typical_damage == 0.0
    assert ch.SKILL_SLOTS["Support"].highest > 0.0
    stated = ch.Skill(name="Bulwark", slot="Support", damage_multiplier=200.0)
    assert stated.weapon_damage_percent() == 200.0


# --------------------------------------------------------------------------
# What this means for the damage already fitted
# --------------------------------------------------------------------------

def test_the_damage_target_is_what_a_basic_attack_does():
    """Which is what makes settling this cost nothing. The tier 8 target and
    every affix value were fitted to an ordinary hit."""
    assert af.damage_for_slot("Basic") == pytest.approx(af.damage_target(8))


def test_the_other_slots_multiply_from_that_target():
    target = af.damage_target(8)
    for slot, expected in (("Heavy", 2.5), ("Special", 1.5), ("Ultimate", 4.0),
                           ("Movement", 1.0), ("Aura", 0.25)):
        assert af.damage_for_slot(slot) == pytest.approx(target * expected)


def test_an_unknown_slot_is_rejected_when_asked_what_it_deals():
    with pytest.raises(ValueError, match="unknown skill slot"):
        af.damage_for_slot("Passive")


def test_settling_this_left_the_weapon_figure_meaning_the_weapon():
    """It used to be the weapon and the skill together, because no skill had a
    multiplier. With the basic attack at 100%, it is the weapon alone."""
    target = af.damage_target(8)
    weapon = af.weapon_base_damage_needed(target, 6, 6)
    assert weapon > 0
    from_affixes = af.FLAT_DAMAGE.value_at(7) * 6
    assert weapon + from_affixes == pytest.approx(
        target / (1 + af.INCREASED_DAMAGE.value_at(7) / 100.0 * 6))


def test_an_ultimate_is_worth_several_common_enemies():
    """A sanity check that the top of the scale means something. At tier 8 an
    Ultimate should clear a pack rather than dent one enemy."""
    from cataclysm_sim import enemy_stats as es
    common = es.stats_on_floor("Common", 8, "Cataclysm")
    assert af.damage_for_slot("Ultimate") > 1.5 * common.effective_health
