"""What a skill is worth, in weapon damage.

Issue #107. The design said every weapon type paired with every damage type
produces a set of skills, and never said what any of them was worth, so every
weapon damage figure in this project was really weapon-and-skill together.
"""

from __future__ import annotations

import csv
import pathlib
import re

import pytest

from cataclysm_sim import affixes as af
from cataclysm_sim import character as ch

WEAPON_SKILLS = (pathlib.Path(__file__).resolve().parents[2]
                 / "game" / "Data" / "WeaponSkills.csv")


# --------------------------------------------------------------------------
# The slots themselves
# --------------------------------------------------------------------------

def test_the_slots_match_the_design_documents_table():
    """`Cataclysm_GDD_v2.md` lists seven rows in its Skill Slots table."""
    assert set(ch.SKILL_SLOTS) == {"Basic", "Heavy", "Special", "Support",
                                   "Aura", "Ultimate", "Movement"}


def test_a_player_chooses_six_of_them():
    """The design says six slots and that the basic attack is automatic, so the
    seventh is not one a player spends."""
    assert len(ch.CHOSEN_SKILL_SLOTS) == 6
    assert ch.BASIC_ATTACK_SLOT not in ch.CHOSEN_SKILL_SLOTS


def test_that_slot_list_check_actually_fires():
    real = dict(ch.SKILL_SLOTS)
    ch.SKILL_SLOTS.pop("Aura")
    try:
        with pytest.raises(ValueError, match="drifted from the design"):
            ch._check_the_slots_match_the_design_document()
    finally:
        ch.SKILL_SLOTS.clear()
        ch.SKILL_SLOTS.update(real)


def test_the_basic_attack_is_exactly_one_hundred_percent():
    """It is the anchor. Every damage figure already fitted -- the tier 8 target,
    the affix values, what a weapon must supply -- was fitted to an ordinary hit,
    and an ordinary hit is the basic attack. If this stopped being 100%, all of
    them would silently mean something else."""
    basic = ch.SKILL_SLOTS[ch.BASIC_ATTACK_SLOT]
    assert basic.typical_damage == basic.lowest == basic.highest == 100.0


def test_that_anchor_check_actually_fires():
    real = ch.SKILL_SLOTS[ch.BASIC_ATTACK_SLOT]
    ch.SKILL_SLOTS[ch.BASIC_ATTACK_SLOT] = ch.SkillSlot(
        "Basic", 120.0, 120.0, 120.0, "moved")
    try:
        with pytest.raises(ValueError, match="must be exactly 100%"):
            ch._check_the_basic_attack_is_the_anchor()
    finally:
        ch.SKILL_SLOTS[ch.BASIC_ATTACK_SLOT] = real


@pytest.mark.parametrize("slot", sorted(ch.SKILL_SLOTS))
def test_every_slots_typical_value_sits_inside_its_own_band(slot):
    s = ch.SKILL_SLOTS[slot]
    assert s.lowest <= s.typical_damage <= s.highest


def test_a_band_that_does_not_contain_its_typical_value_is_rejected():
    with pytest.raises(ValueError, match="outside its"):
        ch.SkillSlot("Bad", 500.0, 100.0, 200.0, "impossible")


def test_the_ultimate_is_the_biggest_hit_and_support_the_smallest():
    """A skill on a long cooldown should be worth more per use than one that is
    off cooldown constantly, and a buff should not be a damage skill."""
    typical = {n: s.typical_damage for n, s in ch.SKILL_SLOTS.items()}
    assert typical["Ultimate"] == max(typical.values())
    assert typical["Support"] == min(typical.values())
    assert typical["Heavy"] > typical["Special"] > typical["Basic"]


# --------------------------------------------------------------------------
# The numbers came out of the designed skills, not out of nowhere
# --------------------------------------------------------------------------

def stated_multipliers(damage_type: str | None = None) -> dict[str, float]:
    """Every skill in the data whose description states a weapon multiplier.

    THIS READS THE GAME DATA, which the simulation package itself never does and
    should not start doing. It is here because these three tests exist to prove
    the slot values were derived from the designed skills rather than invented,
    and that claim cannot be checked against anything else.

    Pass a damage type to restrict the answer to it. The War set is the evidence
    the slot bands were read off, so the test below pins that set exactly; every
    damage type designed afterwards is checked against the bands instead, which
    is the direction the evidence actually runs.
    """
    if not WEAPON_SKILLS.exists():
        raise AssertionError(
            f"{WEAPON_SKILLS} is missing, so the claim that the skill slot "
            "values came from the designed skills cannot be checked. It is "
            "generated by tools/generate_datatables.py.")
    found = {}
    with WEAPON_SKILLS.open(encoding="utf-8-sig") as handle:
        for row in csv.DictReader(handle):
            if damage_type is not None and row["DamageType"] != damage_type:
                continue
            match = re.search(r"(\d+)%\s+weapon damage",
                              row["SkillDescription"] or "", re.I)
            if match:
                found[row["SkillName"]] = float(match.group(1))
    return found


def test_the_designed_skills_already_state_weapon_damage_multipliers():
    """This is why the concept was not invented here. Four of the 61 designed
    War skills in `game/Data/WeaponSkills.csv` say what they are worth in prose.

    Pinned to War on purpose. War was the only complete damage type when the
    slot bands were derived, so it is the evidence for them. A later damage type
    stating its own figure is not evidence and must not silently widen a band;
    it is checked against the bands by the two tests below instead.
    """
    stated = stated_multipliers("War")
    assert stated == {"Haymaker": 100.0, "Bulwark": 200.0,
                      "Annihilator": 300.0, "Skull Splitter": 500.0}


def test_the_ultimate_band_is_the_two_designed_ultimates():
    """Derived rather than picked. Annihilator states 300% and Skull Splitter
    states 500%, so the band is exactly those two."""
    ultimate = ch.SKILL_SLOTS["Ultimate"]
    stated = stated_multipliers()
    assert ultimate.lowest == stated["Annihilator"] == 300.0
    assert ultimate.highest == stated["Skull Splitter"] == 500.0


def test_every_designed_multiplier_fits_inside_some_slots_band():
    """A stated figure outside every band would mean the bands are wrong."""
    bands = [(s.lowest, s.highest) for s in ch.SKILL_SLOTS.values()]
    for name, value in stated_multipliers().items():
        assert any(low <= value <= high for low, high in bands), (
            f"{name} states {value}% and no slot's band contains it")


# --------------------------------------------------------------------------
# A skill knows what it is worth
# --------------------------------------------------------------------------

def test_a_skill_takes_its_slots_value_unless_it_states_its_own():
    assert ch.Skill(name="Swing").weapon_damage_percent() == 100.0
    assert ch.Skill(name="Cleave", slot="Heavy").weapon_damage_percent() == 250.0
    assert ch.Skill(name="Skull Splitter", slot="Ultimate",
                    damage_multiplier=500.0).weapon_damage_percent() == 500.0


def test_a_skill_in_a_slot_that_does_not_exist_is_rejected():
    with pytest.raises(ValueError, match="expected one of"):
        ch.Skill(name="Odd", slot="Passive")


def test_a_skill_dealing_less_than_no_damage_is_rejected():
    with pytest.raises(ValueError, match="less than none"):
        ch.Skill(name="Odd", slot="Heavy", damage_multiplier=-50.0)


def test_a_support_skill_may_still_state_damage_of_its_own():
    """The slot's typical value is zero because most buffs deal none, not
    because a support skill is forbidden from dealing any."""
    assert ch.SKILL_SLOTS["Support"].typical_damage == 0.0
    assert ch.SKILL_SLOTS["Support"].highest > 0.0
    stated = ch.Skill(name="Bulwark", slot="Support", damage_multiplier=200.0)
    assert stated.weapon_damage_percent() == 200.0


# --------------------------------------------------------------------------
# What this means for the damage already fitted
# --------------------------------------------------------------------------

def test_the_damage_target_is_what_a_basic_attack_does():
    """Which is what makes settling this cost nothing. The tier 8 target and
    every affix value were fitted to an ordinary hit."""
    assert af.damage_for_slot("Basic") == pytest.approx(af.damage_target(8))


def test_the_other_slots_multiply_from_that_target():
    target = af.damage_target(8)
    for slot, expected in (("Heavy", 2.5), ("Special", 1.5), ("Ultimate", 4.0),
                           ("Movement", 1.0), ("Aura", 0.25)):
        assert af.damage_for_slot(slot) == pytest.approx(target * expected)


def test_an_unknown_slot_is_rejected_when_asked_what_it_deals():
    with pytest.raises(ValueError, match="unknown skill slot"):
        af.damage_for_slot("Passive")


def test_settling_this_left_the_weapon_figure_meaning_the_weapon():
    """It used to be the weapon and the skill together, because no skill had a
    multiplier. With the basic attack at 100%, it is the weapon alone."""
    target = af.damage_target(8)
    weapon = af.weapon_base_damage_needed(target, 6, 6)
    assert weapon > 0
    from_affixes = af.FLAT_DAMAGE.value_at(7) * 6
    assert weapon + from_affixes == pytest.approx(
        target / (1 + af.INCREASED_DAMAGE.value_at(7) / 100.0 * 6))


def test_an_ultimate_is_worth_several_common_enemies():
    """A sanity check that the top of the scale means something. At tier 8 an
    Ultimate should clear a pack rather than dent one enemy."""
    from cataclysm_sim import enemy_stats as es
    common = es.stats_on_floor("Common", 8, "Cataclysm")
    assert af.damage_for_slot("Ultimate") > 1.5 * common.effective_health


# --------------------------------------------------------------------------
# What a skill costs: cooldown and mana. Issue #155.
#
# Neither existed. The design document defines a cooldown reduction formula, an
# attribute that scales it, an affix that grants it and 41 enchantments that
# mention it, and no skill supplied a base for any of that to divide.
# --------------------------------------------------------------------------

def test_only_the_automatic_slot_and_the_toggle_have_no_cooldown():
    """A cooldown of zero is also what a forgotten cooldown looks like, so the
    two that legitimately have none are named rather than inferred."""
    free = {n for n, s in ch.SKILL_SLOTS.items() if s.typical_cooldown == 0.0}
    assert free == {ch.BASIC_ATTACK_SLOT, "Aura"}
    assert free == set(ch.SLOTS_WITHOUT_A_COOLDOWN)


def test_every_slot_a_player_chooses_is_limited_by_something():
    """A skill with no cooldown and no cost can be held down."""
    for name in ch.CHOSEN_SKILL_SLOTS:
        slot = ch.SKILL_SLOTS[name]
        assert slot.typical_cooldown > 0 or slot.mana_cost_percent > 0, (
            f"{name} costs nothing and waits for nothing")


def test_the_basic_attack_is_the_only_free_slot():
    """The design calls it automatic and free. Everything else is paid for."""
    assert ch.SKILL_SLOTS[ch.BASIC_ATTACK_SLOT].mana_cost_percent == 0.0
    for name in ch.CHOSEN_SKILL_SLOTS:
        assert ch.SKILL_SLOTS[name].mana_cost_percent > 0.0, name


def test_a_cooldown_band_that_does_not_contain_its_typical_is_rejected():
    with pytest.raises(ValueError, match="typical cooldown"):
        ch.SkillSlot("Bad", 100.0, 100.0, 100.0, "impossible",
                     typical_cooldown=30.0, cooldown_lowest=1.0,
                     cooldown_highest=5.0, mana_cost_percent=1.0)


def test_the_ultimate_waits_longest_and_movement_waits_least():
    """The design says the Ultimate is on a long cooldown and calls the Heavy
    Attack's moderate. Ordering them is what makes those words mean something."""
    waits = {n: s.typical_cooldown for n, s in ch.SKILL_SLOTS.items()
             if s.typical_cooldown > 0}
    assert waits["Ultimate"] == max(waits.values())
    assert waits["Movement"] == min(waits.values())
    assert waits["Support"] > waits["Special"] > waits["Heavy"]


def test_a_skill_takes_its_slots_cooldown_when_it_states_none():
    skill = ch.Skill(name="Molten Cleave", slot="Heavy")
    assert skill.base_cooldown() == ch.SKILL_SLOTS["Heavy"].typical_cooldown


def test_a_skill_may_state_its_own_cooldown():
    skill = ch.Skill(name="Odd", slot="Heavy", cooldown=11.0)
    assert skill.base_cooldown() == 11.0


def test_a_negative_cooldown_is_rejected():
    with pytest.raises(ValueError, match="less than none"):
        ch.Skill(name="Impossible", slot="Heavy", cooldown=-1.0)


def test_cooldown_reduction_now_has_something_to_divide():
    """Before this, every point of Efficacy and every cooldown reduction affix
    divided a base of zero. This is the check that issue #155 is actually
    fixed: set a slot's cooldown back to zero and the reduction stops
    mattering, because zero divided by anything is still zero."""
    from cataclysm_sim.classes import DEMONIC_CLASSES

    plain = ch.Character(DEMONIC_CLASSES["Ravager"], level=100,
                         skill=ch.Skill(name="Pyroclasm", slot="Ultimate"))
    invested = ch.Character(DEMONIC_CLASSES["Ravager"], level=100,
                            attributes=ch.Attributes(efficacy=100),
                            skill=ch.Skill(name="Pyroclasm", slot="Ultimate"))
    assert plain.skill_cooldown() == 60.0
    assert invested.skill_cooldown() == pytest.approx(30.0)
    assert invested.skill_cooldown() < plain.skill_cooldown()


def test_mana_cost_is_measured_against_the_class_base_not_the_final_pool():
    """THE LOAD-BEARING ONE. Mind grants 2% maximum mana per point and only 1%
    mana regeneration, and two affixes raise maximum mana as well. If cost were
    a share of the final pool, every one of those would buy nothing, because
    the price would rise with the pool. Measured against the class base, they
    all buy more casts."""
    from cataclysm_sim.classes import DEMONIC_CLASSES

    plain = ch.Character(DEMONIC_CLASSES["Ritualist"], level=100)
    stacked = ch.Character(DEMONIC_CLASSES["Ritualist"], level=100,
                           attributes=ch.Attributes(mind=100),
                           gear=ch.Gear(flat={"max_mana": 200.0},
                                        increased={"max_mana": 0.5}))

    assert stacked.stat("max_mana") > plain.stat("max_mana")
    assert stacked.mana_cost_of("Heavy") == plain.mana_cost_of("Heavy")

    casts_plain = plain.stat("max_mana") / plain.mana_cost_of("Heavy")
    casts_stacked = stacked.stat("max_mana") / stacked.mana_cost_of("Heavy")
    assert casts_stacked > casts_plain


def test_the_aura_actually_runs_out_for_every_demonic_class():
    """Issue #36 requires the aura to switch off when the resource is
    exhausted. If regeneration ever covered the drain it would run forever and
    that acceptance criterion could never be met."""
    from cataclysm_sim.classes import DEMONIC_CLASSES

    for name, definition in DEMONIC_CLASSES.items():
        character = ch.Character(definition, level=100)
        seconds = character.seconds_of_aura()
        assert seconds != float("inf"), (
            f"the {name} aura never runs out, so it can never switch itself off")
        assert 20.0 <= seconds <= 90.0, (
            f"the {name} aura lasts {seconds:.0f}s from a full pool, which is "
            "outside the 20 to 90 seconds a toggled commitment should last")


def test_using_everything_on_cooldown_costs_more_than_regeneration_supplies():
    """Mana has to bind, or the cost is decoration and the four mana affixes
    buy nothing worth having. It must not bind so hard the character cannot
    act, so this checks the ratio rather than only the direction."""
    from cataclysm_sim.classes import DEMONIC_CLASSES

    for name, definition in DEMONIC_CLASSES.items():
        character = ch.Character(definition, level=100)
        spend = sum(
            character.mana_cost_of(s) / ch.SKILL_SLOTS[s].typical_cooldown
            for s in ch.CHOSEN_SKILL_SLOTS
            if ch.SKILL_SLOTS[s].typical_cooldown > 0)
        regen = character.stat("mana_regen")
        assert regen < spend <= 2.5 * regen, (
            f"the {name} spends {spend:.1f} mana/s against {regen:.1f}/s of "
            "regeneration")


def test_the_design_document_cost_table_matches_the_code():
    """The War skill examples table already drifted from the workbook once.
    This stops the cost table drifting from the model it describes."""
    document = (pathlib.Path(__file__).resolve().parents[2]
                / "docs" / "Cataclysm_GDD_v2.md").read_text(encoding="utf-8")
    start = document.find("### **What a Skill Costs**")
    assert start != -1, "the design document has no What a Skill Costs section"
    section = document[start:document.find("### **Skill Acquisition**", start)]

    labels = {ch.BASIC_ATTACK_SLOT: "Basic Attack", "Heavy": "Heavy Attack"}
    checked = 0
    for name, slot in ch.SKILL_SLOTS.items():
        label = labels.get(name, name)
        row = re.search(
            rf"^\| {re.escape(label)} \| ([^|]+?) \| ([^|]+?) \| ([^|]+?) \|",
            section, re.MULTILINE)
        assert row, f"{label} has no row in the cost table"
        checked += 1
        cooldown, band, cost = (g.strip() for g in row.groups())

        if slot.typical_cooldown == 0.0:
            assert cooldown == "none", f"{label} cooldown reads {cooldown!r}"
        else:
            assert cooldown == f"{slot.typical_cooldown:g}s", label
            assert band == (f"{slot.cooldown_lowest:g}–"
                            f"{slot.cooldown_highest:g}s"), label

        if slot.mana_cost_percent == 0.0:
            assert cost == "none", f"{label} cost reads {cost!r}"
        else:
            assert cost.startswith(f"{slot.mana_cost_percent:g}%"), label

    assert checked == len(ch.SKILL_SLOTS)
