"""Dungeon modifiers, generated from the Dungeon Modifiers sheet.

Each entry is (name, score). The sheet's 'Weight' column is used as the
modifier's score, which feeds straight into calculateScores' modifierScore.

NOTE: that column currently does double duty -- it reads like a spawn weight
(higher = more common) but is being consumed as a power score (higher = more
dangerous). That makes the MOST COMMON modifiers also the MOST DANGEROUS,
which is backwards from the usual convention. Flagged, not resolved.
"""

from __future__ import annotations

MODIFIERS: dict[str, list[tuple[str, float]]] = {
    'Celestial': [
        ('Edict of Silence', 20),
        ('Divine Resurgence', 15),
        ('Eternal Chorus', 15),
        ('Forced Tithes', 15),
        ('Holy Repercussions', 15),
        ('Sanctioned Passage', 15),
        ('Angelic Wardens', 10),
        ('Divine Wrath', 10),
        ('Hallowed Groundfall', 10),
        ('Heaven’s Quake', 10),
        ('Lightforged Walls', 10),
        ('Trial of Endurance', 10),
        ('Golden Spires', 5),
        ('Judgment Zones', 5),
        ('Wings of the Host', 5),
    ],
    'Chaos': [
        ('Fragmented Reality', 20),
        ('Reality Twister', 20),
        ('Chaos Touched', 15),
        ('Rule of Chaos', 15),
        ('Unstable Portal', 15),
        ('Chaotic Loot', 10),
        ("Pandora's Box", 10),
        ('Trick or Treat', 10),
        ('Unstable Dimensions', 10),
        ('Volatile Evolution', 10),
        ('Wild Magic', 10),
        ('Echo Chamber', 5),
        ('Illusory Enemies', 5),
        ('Reality Rifts', 5),
        ('The Labrynth', 5),
    ],
    'Death': [
        ('The Reaper', 20),
        ('Echoes of the Past', 15),
        ('Mortal Decay', 15),
        ('Dead Rising', 10),
        ("Death's Embrace", 10),
        ('Dirge Resonance', 10),
        ('Grave Tide', 10),
        ('Necrotic Bloom', 10),
        ('Necrotic Ground', 10),
        ('Obsidian Sarcophagi', 10),
        ('Soul Chains', 10),
        ('Vengful Wraiths', 10),
        ('Cryptquake', 5),
        ('Funereal Procession', 5),
        ('Grim Totems', 5),
    ],
    'Demonic': [
        ('Blood Bond', 20),
        ('Infernal Brand', 20),
        ('Blood Altar', 15),
        ('Abyssal Rifts', 10),
        ('Blood Gates', 10),
        ('Demonic Guide', 10),
        ('Hellfire', 10),
        ('Infernal Beacons', 10),
        ('Infernal Rain', 10),
        ('Infernal Seals', 10),
        ('Soul Harvest', 10),
        ('Blood Price', 5),
        ('Demon Prince', 5),
        ('Pact of Temptation', 5),
    ],
    'Famine': [
        ('Hard Mode', 20),
        ('Starvation', 20),
        ('Dehydration', 15),
        ('Ravenous Hoard', 15),
        ('Scarcity', 15),
        ('Withering Touch', 15),
        ('Desperate Measures', 10),
        ('Diminishing Returns', 10),
        ('Famished Beasts', 10),
        ('Starvation Curse', 10),
        ('Suffering Aura', 10),
        ('Swarm of Locusts', 10),
        ('Luxury Hoarders', 5),
        ('Recession', 5),
        ('Withered Ground', 5),
    ],
    'Pestilence': [
        ('Plague Convergence', 20),
        ('Infection Bloom', 15),
        ('The Plaguebearer', 15),
        ('Carrion Feast', 10),
        ('Contagious Touch', 10),
        ('Epidemic', 10),
        ('Infested Veins', 10),
        ('Leech Spores', 10),
        ('Pestilent Empowerment', 10),
        ('Plague Harbingers', 10),
        ('Raw Sewage', 10),
        ('Spore Clouds', 10),
        ('Fungal Overgrowth', 5),
        ('Quarantine Breach', 5),
        ('The Infested Hoard', 5),
    ],
    'Void': [
        ('The Blackest Shadow', 20),
        ('Those in the Dark', 20),
        ('Insanity Bursts', 15),
        ('Shadowy Enemies', 15),
        ('Singularity Wells', 15),
        ("The Nihil's Embrace", 15),
        ('All Consuming', 10),
        ('Anti-Magic Zones', 10),
        ('Mind-Shattering Illusions', 10),
        ('Portal Unleashing', 10),
        ('Void Parasite', 10),
        ('Grasping Tentacles', 5),
    ],
    'War': [
        ('Supply Lines', 20),
        ('Battlefield Relics', 10),
        ('Battlefield Tactics', 10),
        ('Blood Debt', 10),
        ('Blood-Forged Champions', 10),
        ('Field Medic', 10),
        ('March of Progress', 10),
        ('Royal Guard', 10),
        ('War Banner', 10),
        ('Warzone Control Points', 10),
        ('Artillery Strike', 5),
        ("Commander's Aura", 5),
        ('Fog of War', 5),
        ('Forced March', 5),
        ('Morale Break', 5),
    ],
}

CATACLYSM_TYPES = tuple(sorted(MODIFIERS))
