// Copyright Stephen Dubois. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Abilities/GameplayAbility.h"
#include "AttributeSet.h"
#include "GameplayTagContainer.h"
#include "CataclysmGameplayAbility.generated.h"

/**
 * Which of the seven input slots an ability occupies.
 *
 * The design ties skills to the combination of weapon type and damage type: the
 * equipped weapons determine the POOL of available skills, and the player then
 * assigns chosen skills to slots. This enum is the slot side of that; it is what
 * lets input be bound to "whatever is in the Heavy slot" instead of to a
 * specific ability.
 */
UENUM(BlueprintType)
enum class ECataclysmAbilitySlot : uint8
{
	None		UMETA(DisplayName = "None"),
	BasicAttack	UMETA(DisplayName = "Basic Attack (automatic)"),
	Heavy		UMETA(DisplayName = "Heavy (right mouse)"),
	Special		UMETA(DisplayName = "Special (Q)"),
	Support		UMETA(DisplayName = "Support (W)"),
	Aura		UMETA(DisplayName = "Aura (E, toggle)"),
	Ultimate	UMETA(DisplayName = "Ultimate (R)"),
	Movement	UMETA(DisplayName = "Movement (space)"),
};

/**
 * The slot list, and the single place it is tied to the gameplay tag vocabulary.
 *
 * THE SEVEN SLOTS ARE WRITTEN DOWN TWICE AND THAT IS THE RISK HERE. Once as the
 * enum above, which is hand-written C++ and gives the editor a dropdown, and once
 * as the Slot.* gameplay tags in game/Config/Tags/CataclysmTags.ini, which is
 * generated by tools/generate_gameplay_tags.py from the Tags sheet of
 * docs/All_Things_Cataclysm.xlsx.
 *
 * The workbook is authoritative. The enum is a convenience. If they disagree, an
 * ability authored into a slot is granted a tag that matches no input, and it
 * simply never fires -- nothing errors. Everything that crosses between the two
 * goes through the two functions below, so there is exactly one place to break,
 * and Cataclysm.Input.EveryAbilitySlotHasAGeneratedTag breaks it.
 */
namespace CataclysmAbilitySlots
{
	/** Every slot an ability can occupy. Seven entries; None is not among them. */
	CATACLYSM_API TArrayView<const ECataclysmAbilitySlot> All();

	/** The Slot.* tag naming this slot. An invalid tag for None or an unknown value. */
	CATACLYSM_API FGameplayTag Tag(ECataclysmAbilitySlot Slot);
}

/**
 * Base class for every ability in the game.
 *
 * Defaults to InstancedPerActor. Abilities in this project hold per-activation
 * state -- charge levels, deployable handles, stacking counters -- so the
 * non-instanced policy is not workable, and per-execution instancing allocates
 * far more than is needed.
 */
UCLASS(Abstract)
class CATACLYSM_API UCataclysmGameplayAbility : public UGameplayAbility
{
	GENERATED_BODY()

public:
	UCataclysmGameplayAbility();

	/** Which input slot this ability is designed to sit in. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Cataclysm|Ability")
	ECataclysmAbilitySlot Slot = ECataclysmAbilitySlot::None;

	/**
	 * Activate as soon as the ability is granted, and keep it active.
	 * Used for passive effects and for auras before the player toggles them.
	 */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Cataclysm|Ability")
	bool bActivateOnGranted = false;

	/**
	 * What to call this ability somewhere a player can read it.
	 *
	 * EMPTY ON THE BASE, AND THAT IS THE HONEST ANSWER RATHER THAN A GAP. An
	 * ability with no designed name has none to give. A caller that needs
	 * something to write falls back to the slot's own name, which is what
	 * `UCataclysmSkillBar::NameForEmptySlot` is for.
	 *
	 * WHY A FUNCTION RATHER THAN A FIELD READ DIRECTLY. Two subclasses carry a
	 * `SkillName` of their own -- `UCataclysmSkillTemplate` for a skill that has
	 * numbers and `UCataclysmUndesignedSkill` for one that does not -- and they
	 * are separate fields on separate classes. Without this, anything wanting a
	 * name would have to know about both and try each in turn, and would silently
	 * miss a third when one is added.
	 */
	UFUNCTION(BlueprintPure, Category = "Cataclysm|Ability")
	virtual FString DisplayedName() const;

	/**
	 * Seconds before this ability can be used again. Negative means take the
	 * slot's figure, which is what every designed skill does.
	 *
	 * A skill states its own only when it differs from its slot, exactly as it
	 * does for the weapon damage multiplier. None of the 77 designed skills
	 * states one yet.
	 */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Cataclysm|Ability")
	float CooldownOverride = -1.0f;

	/** Mana this ability costs at level 100. Negative means take the slot's. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Cataclysm|Ability")
	float ManaCostOverride = -1.0f;

	/**
	 * Percent of weapon damage one use deals. Negative takes the slot's.
	 *
	 * THE THIRD OF THE THREE, AND IT ARRIVED LAST FOR A REASON. The other
	 * two above were built when a skill could only sit in the slot it was
	 * designed for, so they were for the rare skill that differed. On
	 * 2026-08-22 the project owner decided a slot is a key and any skill
	 * may go in any slot, which makes all three the ordinary case rather
	 * than the exception: a skill has to be worth what it is worth
	 * wherever it is put. See `docs/DECISIONS.md` and issue #836.
	 *
	 * EVERY SKILL IN THE GAME IS STILL -1, so nothing behaves differently
	 * yet. The mechanism landed before the numbers on purpose.
	 */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Cataclysm|Ability")
	float DamagePercentOverride = -1.0f;

	/** Seconds this ability waits, before any cooldown reduction. */
	UFUNCTION(BlueprintPure, Category = "Cataclysm|Ability")
	float GetBaseCooldown() const;

	/**
	 * Seconds a cooldown of this length waits for this character.
	 *
	 * IT DIVIDES RATHER THAN SUBTRACTING, which the design states and which is
	 * what keeps it from breaking: "Subtracting 1% per point would reach zero
	 * cooldowns at 100 points of Efficacy. Dividing, all 100 points halve every
	 * cooldown, gear pushes further with each point worth progressively less,
	 * and zero is unreachable. No cap is needed, and no point is ever wasted."
	 *
	 * THE ARITHMETIC ALREADY EXISTED AND NOTHING CALLED IT.
	 * UCataclysmCombatAttributeSet::FinalCooldown was written, documented and
	 * tested, and every cooldown in the game was applied at its base length, so
	 * `Stat_Increased_cooldown_reduction` was worth nothing. Issue #895.
	 *
	 * AND IT LENGTHENS IT TOO, despite the name. Issue #1994. The stat
	 * `cooldown_lengthening` multiplies what the reduction leaves, floored so a
	 * negative row shortens nothing: Base x (1 + lengthening) / divisor. The
	 * name was kept because every caller and test asks it by this name, and it
	 * is still the one place a cooldown's length is worked out.
	 *
	 * A PERCENTAGE HERE AND A FRACTION THERE. The `CooldownReduction` attribute
	 * holds a percentage, because that is what an affix grants, and FinalCooldown
	 * takes a fraction. This is where the two meet, and it is the only place
	 * that conversion happens.
	 *
	 * THE CHARACTER'S ROWS WHEN IT HAS ANY, AND THE ATTRIBUTE OTHERWISE. Issue
	 * #1981. `UCataclysmPlayerClassStats::ApplyTo` writes the attribute with an
	 * EMPTY tag container and the default conditions, so a `cooldown_reduction`
	 * row carrying RequiredTags, a Condition or a Scale never reached it and
	 * changed no cooldown in play. The rows are kept on the component for
	 * exactly this, and `UCataclysmAbilitySystemComponent::StatForSkill` is
	 * the lookup that reads them.
	 *
	 * THE ASKED-FOR FIGURE IS THE REDUCTION, NOT THE INTERVAL, and that is the
	 * correction issue #2000 made. The first attempt worked the whole interval
	 * out in one go through a rate route whose divisor is built from the
	 * INCREASES bucket, while the game's data puts cooldown reduction in the
	 * FLAT bucket: the `Haste` affix is `ValueKind` flat, and the Efficacy
	 * attribute contributes an increase whose purpose is to SCALE a base
	 * something else supplied. So the gear read as nothing and the attribute
	 * read as the reduction itself. Asking for the figure and dividing by it
	 * here is what the attribute route always did, with the skill's tags and
	 * conditions now honoured.
	 *
	 * @param AbilitySystem  whose cooldown it is, or null for the base length
	 * @param SkillTags      what this skill is, so a scoped row reaches only the
	 *                       skills it names. Empty means every unscoped row
	 *                       applies and no scoped one does
	 */
	static float CooldownAfterReduction(
		const UAbilitySystemComponent* AbilitySystem, float BaseCooldown,
		const FGameplayTagContainer& SkillTags = FGameplayTagContainer());

	/**
	 * Apply one cooldown: a duration effect of `Seconds` granting `Tag` and
	 * nothing else. What `ApplyCooldown` did inline until issue #1833's skill
	 * charges, moved here so that a charge's recharge starting again, in
	 * `UCataclysmAbilitySystemComponent`, builds exactly the same effect.
	 */
	static void ApplyCooldownEffect(UAbilitySystemComponent* AbilitySystem,
									const FGameplayTag& Tag, float Seconds);

	/** Mana one use costs for the character holding it, at their level. */
	UFUNCTION(BlueprintPure, Category = "Cataclysm|Ability")
	float GetManaCost() const;

	/**
	 * The tags a stat asked for this skill is scoped by. Empty here. Issue #1815.
	 *
	 * A SKILL'S TAGS LIVE ON `UCataclysmSkillTemplate::SkillTags`, a subclass of
	 * this one, and an enemy's C++ ability has none at all. This virtual is how a
	 * cost lookup on the base class reaches them, so that "Your spells cost
	 * 10%-20% less mana" reaches spells and nothing else.
	 *
	 * EMPTY MEANS EVERY UNSCOPED MODIFIER APPLIES, which is what an ability with
	 * no tags of its own should get: a row scoped to a keyword simply does not
	 * reach it.
	 */
	virtual const FGameplayTagContainer& SkillTagsForStats() const;

	/**
	 * What one use costs THIS character, after the `mana_cost` stat. Issue #1815.
	 *
	 * THE ONE PLACE THE STAT IS ASKED, and every reader of a cost goes through
	 * it: `CheckCost`, `ApplyCost`, an aura's per-pulse upkeep in
	 * `UCataclysmAuraSkill::Pulse`, and `UCataclysmSkillBar`, which greys out a
	 * box the character cannot pay for. A reader left on `GetManaCost` would show
	 * or refuse one number while the game charged another, and that disagreement
	 * is the thing this function exists to make impossible.
	 *
	 * THE SKILL'S OWN COST IS THE BASE, so a character with no row is handed it
	 * back unchanged, and `removed` -- the kind issue #1791 added -- is what
	 * "costs no mana" means.
	 *
	 * NEVER BELOW ZERO. A More multiplier cannot reach it, because
	 * `LessMultiplierFloor` stops at -99%, but a negative flat row could, and a
	 * cost below zero would pay the caster for casting.
	 *
	 * @param AbilitySystem  whose cost it is. An ability system this project did
	 *                       not make carries no stat line, so it gets the base.
	 */
	float ManaCostFor(const UAbilitySystemComponent* AbilitySystem) const;

	/**
	 * The share of current health a cast of this skill pays INSTEAD of its mana
	 * cost right now, as a percentage, or nothing. Issues #1820 and #41.
	 *
	 * ONE SOURCE TODAY: the dungeon floor rule `Famine_Desperate_Measures`, "When
	 * your Mana falls below 10%, your skills cost 5% of your current Health to
	 * cast instead of Mana." It writes `ManaCostAsCurrentHealthPercentStat` under
	 * the condition `mana_below`, so the condition is judged when this is asked.
	 *
	 * NOTHING UNLESS THE CAST WOULD HAVE TAKEN MANA, which is the reading ruled
	 * under the project owner's delegation on 2026-09-23: "instead of Mana"
	 * replaces a cost and does not add one. So it answers nothing when
	 * `ManaCostFor` is nothing -- the basic attack, or a skill whose cost the
	 * character's own reductions removed -- and nothing when `CostPool` is health,
	 * because a character whose costs are paid from health would not have paid
	 * mana either.
	 *
	 * `ManaCostFor` AND NOT THE ROW'S BASE COST decides "would have cost mana",
	 * because it is the cost after the character's reductions: a skill that gear
	 * made free would not have cost mana, whatever its slot states.
	 */
	float ManaCostPaidAsHealthPercent(const UAbilitySystemComponent* AbilitySystem) const;

	/**
	 * What the last cast of this skill paid in current health instead of mana, as
	 * a percentage, or nothing. Recorded by `ApplyCost` and read by
	 * `UCataclysmSkillTemplate::PayHealthCost`. Issues #1820 and #41.
	 *
	 * RECORDED ONCE, AT THE PAYMENT, AND NOT ASKED AGAIN. The condition is a
	 * reading of the mana in hand, and paying the mana cost moves it: a cast
	 * taken from 12% mana down to 8% paid in mana, and asking again afterwards
	 * would charge it health as well.
	 */
	float ManaCostPaidAsHealthPercentThisCast() const
	{
		return LastManaCostPaidAsHealthPercent;
	}

	/** `mana_cost_as_current_health_percent`. See `ManaCostPaidAsHealthPercent`. */
	static const TCHAR* ManaCostAsCurrentHealthPercentStat;

	/**
	 * Mana one landed use RETURNS to the character holding it, at their level.
	 *
	 * ONLY THE BASIC ATTACK HAS ONE. game/Data/SkillSlots.csv gives the Basic
	 * row a mana-on-hit of 6 and every other row zero, and the design explains
	 * why that is not a generator to be played around: "The basic attack is
	 * automatic. There is no button to press and no rotation to perform. It is
	 * income for being in a fight rather than a filler action."
	 *
	 * PAID WHEN A HIT LANDS, NOT WHEN A SKILL IS USED.
	 * UCataclysmSkillTemplate::HitTargets pays it, and only when the skill
	 * actually dealt damage, which is what "each time it lands" means. Until
	 * issue #653 nothing read this figure at all: it was loaded from the table
	 * into a field that only tests referenced.
	 */
	UFUNCTION(BlueprintPure, Category = "Cataclysm|Ability")
	float GetManaOnHit() const;

	virtual void OnAvatarSet(const FGameplayAbilityActorInfo* ActorInfo,
							 const FGameplayAbilitySpec& Spec) override;

	// --- Cost and cooldown -------------------------------------------------
	//
	// Overridden rather than driven by a Gameplay Effect asset, because the
	// numbers come from a generated data table and there is no authored asset
	// per slot to put them in. Both halves of each pair are overridden together:
	// a Check without its Apply lets an ability fire forever, which is the
	// failure that leaves no trace.

	/**
	 * The pool a character pays a skill's mana cost from: HEALTH for one that
	 * traded its mana pool for it, MANA for everyone else. Issue #1067.
	 *
	 * ONE ANSWER FOR EVERY PAYER, which is why it is a function. The activation
	 * cost asked this and `UCataclysmAuraSkill::Pulse` did not, so an aura
	 * switched on by a character with no mana pool switched itself off at its
	 * first pulse. Issue #1901.
	 */
	static FGameplayAttribute CostPool(const UAbilitySystemComponent* AbilitySystem);

	/** Whether `Pool` covers `Cost`: strictly more for health, at least for mana. */
	static bool PoolCovers(const UAbilitySystemComponent* AbilitySystem,
						   const FGameplayAttribute& Pool, float Cost);

	/**
	 * Cast from Ward's flag, the Ritualist's 50 point option 3. Issue #1515: "A
	 * skill may be paid for with Energy Shield when your mana is not enough."
	 * Above zero means the option is held.
	 */
	static const TCHAR* CostPaidFromEnergyShieldStat;

	/**
	 * THIS USE IS FOLLOW THROUGH'S FREE REPEAT, and not a use at all. Issue
	 * #1515, ruled 2026-09-24: it pays no mana and no health, starts no cooldown
	 * and waits for none, spends no next-use charge and raises no skill_use.
	 * `CheckCost` and `CheckCooldown` answer yes for it, and
	 * `UCataclysmSkillTemplate::CommitAndBegin` skips everything a use pays or
	 * opens. Set by `UCataclysmFollowThrough` just before it activates the
	 * repeat, and cleared when that use ends.
	 */
	bool bFreeRepeat = false;

	/**
	 * The pool that pays `Cost` for this character now, or an invalid attribute
	 * if none can. Issue #1515.
	 *
	 * `CostPool` FIRST, AS IT ALWAYS WAS. Then, when that pool is mana and cannot
	 * cover the cost, the ENERGY SHIELD if Cast from Ward is held and the shield
	 * can cover it. JUDGEMENT: the whole cost from one pool, the mana left
	 * untouched, since the sentence says the skill is "paid for with Energy
	 * Shield". A character whose mana became health (Water to Blood) never
	 * reaches the shield: "when your mana is not enough" asks about mana.
	 *
	 * ONE ANSWER FOR EVERY PAYER, as `CostPool` is: the cast's check and payment,
	 * an aura's upkeep and the skill bar all ask this.
	 */
	static FGameplayAttribute PoolPaying(const UAbilitySystemComponent* AbilitySystem,
										 float Cost);

	virtual bool CheckCost(const FGameplayAbilitySpecHandle Handle,
						   const FGameplayAbilityActorInfo* ActorInfo,
						   FGameplayTagContainer* OptionalRelevantTags) const override;

	virtual void ApplyCost(const FGameplayAbilitySpecHandle Handle,
						   const FGameplayAbilityActorInfo* ActorInfo,
						   const FGameplayAbilityActivationInfo ActivationInfo) const override;

	virtual bool CheckCooldown(const FGameplayAbilitySpecHandle Handle,
							   const FGameplayAbilityActorInfo* ActorInfo,
							   FGameplayTagContainer* OptionalRelevantTags) const override;

	virtual void ApplyCooldown(const FGameplayAbilitySpecHandle Handle,
							   const FGameplayAbilityActorInfo* ActorInfo,
							   const FGameplayAbilityActivationInfo ActivationInfo) const override;

	/**
	 * Whether this use of the skill skips its cooldown entirely. Issue #973.
	 *
	 * THE MASOCHIST'S THE CATALYST NODE IS THE ONLY SOURCE: "While at or below
	 * 5% health, your skills have a 5% chance per point not to go on cooldown."
	 *
	 * THE CHANCE IS ASKED FOR RATHER THAN READ OFF THE ATTRIBUTE, because the
	 * only source carries a health condition and a conditional bonus is never
	 * folded into a gameplay attribute. That attribute is zero at all times.
	 *
	 * FALSE FOR A CHARACTER WITH NO CHANCE, and no roll is made for one. This is
	 * on the path of every skill use.
	 *
	 * `Cataclysm.CooldownSkipRoll` pins the roll, the way `Cataclysm.CritRoll`
	 * pins the critical strike roll, so a test can assert rather than sample.
	 */
	bool CooldownIsSkipped(const UAbilitySystemComponent* AbilitySystem) const;

private:
	/**
	 * Reads this ability's slot numbers out of the generated table, once.
	 *
	 * Cached because CheckCost runs every time input asks whether an ability can
	 * fire, which is far more often than it activates.
	 */
	void EnsureSlotNumbersLoaded() const;

	mutable bool bSlotNumbersLoaded = false;
	mutable float SlotCooldown = 0.0f;
	mutable float SlotManaCostAtLevel100 = 0.0f;
	mutable float SlotManaOnHitAtLevel100 = 0.0f;

	/**
	 * See `ManaCostPaidAsHealthPercentThisCast`. MUTABLE BECAUSE `ApplyCost` IS
	 * CONST in the engine's declaration, and the payment is the one moment the
	 * answer is known; the three fields above are mutable for the same kind of
	 * reason.
	 */
	mutable float LastManaCostPaidAsHealthPercent = 0.0f;
};
